### ISSUE TITLE
Support build on linux-arm64 ?

### ISSUE THREAD

**Issue by kif** [conda-forge/pyfai-feedstock#63]
### Comment:

Some users are struggling with the installation of pyFAI within a docker onto a MacM1 ...
https://github.com/silx-kit/pyFAI/issues/1896

**Comment by t20100** [comment]
pyfai was added to linux-aarch64 migration last year: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2832 (doc: https://conda-forge.org/docs/maintainer/knowledge_base.html#using-arch-rebuild-txt)

There is probably a dependency that has issue with linux-aarch64.

**Comment by t20100** [comment]
Checking [aarch64 migration status](https://conda-forge.org/status/#aarch64andppc64leaddition), both silx and pyfai are waiting for pyqt migration.

**Comment by t20100** [comment]
I'm trying to add `linux-aarch64` build to silx-base: https://github.com/conda-forge/silx-feedstock/pull/50

**Comment by t20100** [comment]
This was added in PR #64 for `pyfai-base` and `pyqt` is now available on `aarch64` (and `ppc64le`)
